### ISSUE TITLE
no work

### ISSUE THREAD

**Issue by Hunter-171** [Body-Alhoha/Remake#4]
hoW TO USE

**Comment by sigmaclientwastaken** [comment]
yes please give usage tutorial @Body-Alhoha

**Comment by Body-Alhoha** [comment]
Look in the readme, I'll make a tutorial soon

**Comment by Hunter-171** [comment]
btw what is this actually for (purpose)

**Comment by Body-Alhoha** [comment]
u can use this to make injectable mc clients, basically you can modify a java class while the jvm is running
